# Generated by Django 4.2.5 on 2023-09-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='https://logowik.com/content/uploads/images/795_home.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
